name: Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: package.json

      - name: Install dependencies
        run: pnpm install
        
      - name: Run check
        run: pnpm run check
